stages:
  - build
  - test
  - deploy

test:
  stage: test
  image: node
  script:
    - echo "Testing App"
    - CI=true yarn test
    - echo "Test successfully!"
    
build:
  stage: build
  image: node
  script: 
    - echo "Start building App"
    - yarn install
    - yarn build
    - echo "Build successfully!"

deploy:
  stage: deploy
  image: nginx:alpine
  script:
    - echo "Deploying App"
    - CI=true yarn test
    - echo "Test successfully!"
  when: manual

