stages:
  - test
  - docker-build
  - deploy

test:
  stage: test
  image: node
  script:
    - echo "Testing App"
    - yarn install
    - CI=true yarn test
    - echo "Test successfully!"

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - name: docker:19.03.8-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
    - echo "Registry image:" $CI_REGISTRY_IMAGE
  when: manual

deploy:
  stage: deploy
  before_script:
    - echo "deploying app"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull "$CI_REGISTRY_IMAGE"
    - docker stop da_front || true && docker rm da_front || true
    - docker run -p 80:80 -d --name da_front "$CI_REGISTRY_IMAGE"
  tags:
    - deploy
  when: manual
