version: '3.7'
services:
  frontend:
    image: node:14.9.0-alpine3.12
    command: sh -c "yarn && yarn start"
    working_dir: /app
    environment:
      - PORT=8082
    ports:
      - 8082:8082
    volumes:
      - .:/app
